Repository jbsparrow/CyberDropDownloader, pull requests merged in 2024-12, with the labels that each got.

#346 chore: pin aiolimiter to v1.1.0
  poetry.lock
  pyproject.toml
  scripts/release/start_linux.sh
  scripts/release/start_macOS.command
  scripts/release/start_windows.bat
Labels: chore

#341 refactor: modifications to transfer to new hash table process => create backups and simplify
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/utils/database/tables/hash_table.py
  cyberdrop_dl/utils/transfer/backup.py
  cyberdrop_dl/utils/transfer/db_setup.py
  cyberdrop_dl/utils/transfer/transfer_hash_db.py
  cyberdrop_dl/utils/transfer/wrapper.py
Labels: refactor

#353 fix: general fixes
  cyberdrop_dl/main.py
  cyberdrop_dl/managers/config_manager.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
Labels: bug

#351 refactor: redact username from logs
  cyberdrop_dl/utils/logger.py
Labels: refactor

#347 fix: clear program_ui before async_startup
  cyberdrop_dl/ui/program_ui.py
Labels: bug

#352 fix: allow duplicate files download on the same run with --ignore-history
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/managers/client_manager.py
Labels: bug

#340 fix: pydantic config settings fixes
  cyberdrop_dl/config_definitions/authentication_settings.py
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/config_definitions/custom_types.py
  cyberdrop_dl/config_definitions/global_settings.py
  cyberdrop_dl/main.py
  cyberdrop_dl/managers/config_manager.py
  cyberdrop_dl/managers/log_manager.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/managers/path_manager.py
  cyberdrop_dl/ui/prompts/user_prompts.py
  cyberdrop_dl/utils/args.py
  cyberdrop_dl/utils/constants.py
  cyberdrop_dl/utils/cookie_extraction.py
  cyberdrop_dl/utils/data_enums_classes/supported_domains.py
  cyberdrop_dl/utils/yaml.py
  poetry.lock
  pyproject.toml
Labels: bug

#342 fix: v4 import to pydantic config
  cyberdrop_dl/config_definitions/custom_types.py
  cyberdrop_dl/utils/transfer/db_setup.py
  cyberdrop_dl/utils/transfer/transfer_v4_config.py
Labels: bug

#331 docs: wiki updates for pydantic config
  README.md
  docs/.gitbook/assets/Screen Shot 2024-09-23 at 11.09.50.png
  docs/.gitbook/assets/authentication
  docs/.gitbook/assets/cli arguments
  docs/.gitbook/assets/configuration options
  docs/.gitbook/assets/cyberdrop dl install advanced
  docs/.gitbook/assets/cyberdrop dl install easy
  docs/.gitbook/assets/global settings
  docs/.gitbook/assets/python install linux
  docs/.gitbook/assets/python install mac
  docs/.gitbook/assets/python install windows
  docs/.gitbook/assets/quick start
  docs/.gitbook/assets/settings
  docs/README.md
  docs/SUMMARY.md
  docs/assets/cyberdrop-dl_tui_preview.png
  docs/assets/reddit_personal_script_setup_1.png
  docs/assets/reddit_personal_script_setup_2.png
  docs/frequently-asked-questions.md
  docs/getting-started/README.md
  docs/getting-started/cyberdrop-dl-install.md
  docs/getting-started/python-install/README.md
  docs/getting-started/python-install/linux.md
  docs/getting-started/python-install/macos.md
  docs/getting-started/python-install/windows.md
  docs/migration-to-cyberdrop-dl-patched.md
  docs/quick-start/README.md
  docs/quick-start/cyberdrop-dl-install-advanced.md
  docs/quick-start/cyberdrop-dl-install-easy.md
  docs/quick-start/python-install-linux.md
  docs/quick-start/python-install-mac.md
  docs/quick-start/python-install-windows.md
  docs/reference/cli-arguments.md
  docs/reference/configuration-options/README.md
  docs/reference/configuration-options/authentication.md
  docs/reference/configuration-options/global-settings.md
  docs/reference/configuration-options/global-settings/README.md
  docs/reference/configuration-options/global-settings/general.md
  docs/reference/configuration-options/global-settings/rate-limiting-options.md
  docs/reference/configuration-options/global-settings/ui-options.md
  docs/reference/configuration-options/image.png
  docs/reference/configuration-options/settings.md
  docs/reference/configuration-options/settings/README.md
  docs/reference/configuration-options/settings/browser_cookies.md
  docs/reference/configuration-options/settings/download_options.md
  docs/reference/configuration-options/settings/dupe_cleanup_options.md
  docs/reference/configuration-options/settings/file_size_limits.md
  docs/reference/configuration-options/settings/files.md
  docs/reference/configuration-options/settings/ignore_options.md
  docs/reference/configuration-options/settings/logs.md
  docs/reference/configuration-options/settings/runtime_options.md
  docs/reference/configuration-options/settings/sorting.md
  docs/reference/notifications.md
  docs/reference/supported-websites.md
  docs/simpcity-support-dropped.md
  docs/transition-from-v4-to-v5.md
  docs/transition-to-v6.md
Labels: documentation

#355 fix: sorting
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/main.py
  cyberdrop_dl/managers/log_manager.py
  cyberdrop_dl/managers/path_manager.py
  cyberdrop_dl/ui/progress/sort_progress.py
  cyberdrop_dl/utils/args.py
  cyberdrop_dl/utils/sorting.py
Labels: bug

#348 fix: forum post parsing
  cyberdrop_dl/scraper/crawlers/celebforum_crawler.py
  cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
  cyberdrop_dl/scraper/crawlers/leakedmodels_crawler.py
  cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
  cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
  cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
  cyberdrop_dl/scraper/crawlers/xbunker_crawler.py
Labels: bug

#356 fix: update gofile crawler to new design
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/scraper/crawlers/gofile_crawler.py
  cyberdrop_dl/utils/sorting.py
Labels: bug

#359 fix: do not use aiolimiter.compat
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/managers/download_speed_manager.py
  cyberdrop_dl/managers/leaky.py
  poetry.lock
  pyproject.toml
Labels: bug

#366 chore: update poetry dependencies
  poetry.lock
  pyproject.toml
Labels: chore

#354 refactor: unify all forums into a single XenForo crawler
  cyberdrop_dl/main.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/celebforum_crawler.py
  cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
  cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
  cyberdrop_dl/scraper/crawlers/leakedmodels_crawler.py
  cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
  cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
  cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
  cyberdrop_dl/scraper/crawlers/xbunker_crawler.py
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
Labels: refactor

#363 fix: asyncio lock fixes
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/managers/db_manager.py
  cyberdrop_dl/managers/download_manager.py
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/ui/progress/file_progress.py
  cyberdrop_dl/utils/database/table_definitions.py
  cyberdrop_dl/utils/database/tables/temp_table.py
  cyberdrop_dl/utils/transfer/transfer_v4_db.py
  cyberdrop_dl/utils/utilities.py
Labels: bug

#371 ci: replace issue templates with issue forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement

#370 docs: wiki and changelog updates for v6.0 release
  CHANGELOG.md
  docs/reference/cli-arguments.md
  docs/reference/configuration-options/settings/sorting.md
  docs/transition-to-v6.md
Labels: documentation

#365 refactor: get supported domains from crawlers
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
  cyberdrop_dl/scraper/crawlers/celebforum_crawler.py
  cyberdrop_dl/scraper/crawlers/coomer_crawler.py
  cyberdrop_dl/scraper/crawlers/cyberdrop_crawler.py
  cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py
  cyberdrop_dl/scraper/crawlers/ehentai_crawler.py
  cyberdrop_dl/scraper/crawlers/erome_crawler.py
  cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
  cyberdrop_dl/scraper/crawlers/fapello_crawler.py
  cyberdrop_dl/scraper/crawlers/gofile_crawler.py
  cyberdrop_dl/scraper/crawlers/hotpic_crawler.py
  cyberdrop_dl/scraper/crawlers/imageban_crawler.py
  cyberdrop_dl/scraper/crawlers/imgbb_crawler.py
  cyberdrop_dl/scraper/crawlers/imgbox_crawler.py
  cyberdrop_dl/scraper/crawlers/imgur_crawler.py
  cyberdrop_dl/scraper/crawlers/kemono_crawler.py
  cyberdrop_dl/scraper/crawlers/leakedmodels_crawler.py
  cyberdrop_dl/scraper/crawlers/mediafire_crawler.py
  cyberdrop_dl/scraper/crawlers/nekohouse_crawler.py
  cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
  cyberdrop_dl/scraper/crawlers/nudostartv_crawler.py
  cyberdrop_dl/scraper/crawlers/omegascans_crawler.py
  cyberdrop_dl/scraper/crawlers/pimpandhost_crawler.py
  cyberdrop_dl/scraper/crawlers/pixeldrain_crawler.py
  cyberdrop_dl/scraper/crawlers/postimg_crawler.py
  cyberdrop_dl/scraper/crawlers/realbooru_crawler.py
  cyberdrop_dl/scraper/crawlers/realdebrid_crawler.py
  cyberdrop_dl/scraper/crawlers/reddit_crawler.py
  cyberdrop_dl/scraper/crawlers/redgifs_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34vault_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34xxx_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34xyz_crawler.py
  cyberdrop_dl/scraper/crawlers/saint_crawler.py
  cyberdrop_dl/scraper/crawlers/scrolller_crawler.py
  cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
  cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
  cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py
  cyberdrop_dl/scraper/crawlers/toonily_crawler.py
  cyberdrop_dl/scraper/crawlers/xbunker_crawler.py
  cyberdrop_dl/scraper/crawlers/xbunkr_crawler.py
  cyberdrop_dl/scraper/crawlers/xxxbunker_crawler.py
  cyberdrop_dl/ui/prompts/user_prompts.py
  cyberdrop_dl/utils/cookie_management.py
  cyberdrop_dl/utils/data_enums_classes/supported_domains.py
  docs/reference/configuration-options/settings/browser_cookies.md
  pyproject.toml
Labels: refactor

#378 chore: switch back to Pypi `browser-cookie3`
  cyberdrop_dl/dependencies/browser_cookie3/__init__.py
  cyberdrop_dl/ui/program_ui.py
  cyberdrop_dl/utils/cookie_management.py
  poetry.lock
  pyproject.toml
Labels: chore

#379 fix: cookie import error log
  cyberdrop_dl/ui/program_ui.py
  cyberdrop_dl/ui/prompts/user_prompts.py
  cyberdrop_dl/utils/cookie_management.py
Labels: bug

#376 Implement caching into master for v6.0 release
  CHANGELOG.md
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/config_definitions/global_settings.py
  cyberdrop_dl/managers/cache_manager.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/managers/path_manager.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
  cyberdrop_dl/scraper/crawlers/coomer_crawler.py
  cyberdrop_dl/scraper/crawlers/kemono_crawler.py
  cyberdrop_dl/scraper/crawlers/reddit_crawler.py
  cyberdrop_dl/scraper/filters.py
  cyberdrop_dl/ui/program_ui.py
  cyberdrop_dl/ui/prompts/user_prompts.py
  cyberdrop_dl/utils/args.py
  cyberdrop_dl/utils/data_enums_classes/hash.py
  cyberdrop_dl/utils/sorting.py
  cyberdrop_dl/utils/yaml.py
  docs/reference/cli-arguments.md
  docs/reference/configuration-options/global-settings/rate-limiting-options.md
  docs/transition-to-v6.md
  poetry.lock
  pyproject.toml
  scripts/release/start_linux.sh
  scripts/release/start_macOS.command
  scripts/release/start_windows.bat
Labels: documentation, enhancement, refactor, chore

#381 fix: override cdn on albums (bunkr)
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
Labels: bug

#384 refactor: log downloads skipped by ignore extension config
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/managers/download_manager.py
Labels: refactor

#385 refactor: send media files straight to downloader
  cyberdrop_dl/scraper/crawlers/coomer_crawler.py
  cyberdrop_dl/scraper/crawlers/kemono_crawler.py
  cyberdrop_dl/scraper/crawlers/nekohouse_crawler.py
Labels: refactor

#388 fix: sorting incremeter logic
  cyberdrop_dl/utils/sorting.py
Labels: bug

#392 fix: v5 to v6 database transfer
  cyberdrop_dl/utils/transfer/transfer_hash_db.py
  pyproject.toml
Labels: bug

#391 ci/cd: update GH release workflow + ruff pre-commit hook
  .github/workflows/create_release.yaml
  .pre-commit-config.yaml
Labels: ci/cd

#394 fix: fallback to old file password check (cyberfile)
  cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py
Labels: bug

#399 refactor: set 512MB as the minimun required free space
  cyberdrop_dl/config_definitions/global_settings.py
  docs/reference/configuration-options/global-settings/general.md
Labels: refactor

#398 fix: handle stream redirects (bunkr)
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/managers/config_manager.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
  docs/reference/configuration-options/settings/runtime_options.md
Labels: bug

#393 fix: `scrape_item` references
  cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py
  cyberdrop_dl/scraper/crawlers/omegascans_crawler.py
Labels: bug

#400 refactor: update log settings
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/utils/logger.py
  docs/reference/configuration-options/settings/runtime_options.md
Labels: documentation, refactor

#401 refactor: redact traceback logs
  cyberdrop_dl/main.py
  cyberdrop_dl/utils/logger.py
Labels: refactor

#402 refactor: add `--output-folder` to deprecated args
  CHANGELOG.md
  cyberdrop_dl/utils/args.py
Labels: refactor

#403 feat: allow any file name for cookie files
  cyberdrop_dl/main.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/scraper.py
  docs/reference/configuration-options/settings/browser_cookies.md
Labels: documentation, enhancement, refactor

#404 feat: add `--separate-posts-format`
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/coomer_crawler.py
  cyberdrop_dl/scraper/crawlers/kemono_crawler.py
  cyberdrop_dl/scraper/crawlers/nekohouse_crawler.py
  cyberdrop_dl/scraper/crawlers/reddit_crawler.py
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
  docs/reference/cli-arguments.md
  docs/reference/configuration-options/settings/download_options.md
Labels: enhancement

#413 fix: file upload date parsing
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
Labels: bug

#414 fix: miscalculation of download queue length
  cyberdrop_dl/ui/progress/file_progress.py
  cyberdrop_dl/ui/progress/scraping_progress.py
  cyberdrop_dl/utils/utilities.py
Labels: bug

#415 fix: sanitize custom filenames
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
  cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py
  cyberdrop_dl/scraper/crawlers/xxxbunker_crawler.py
Labels: bug

#408 fix: `AppriseURL` parsing
  .gitignore
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/config_definitions/custom_types.py
  cyberdrop_dl/main.py
  cyberdrop_dl/managers/config_manager.py
  cyberdrop_dl/utils/apprise.py
  cyberdrop_dl/utils/args.py
  cyberdrop_dl/utils/constants.py
  cyberdrop_dl/utils/logger.py
  cyberdrop_dl/utils/utilities.py
  cyberdrop_dl/utils/yaml.py
  docs/reference/notifications.md
  poetry.lock
  pyproject.toml
  tests/fake_classes/managers.py
  tests/test_apprise.py
  tests/test_files/apprise/empty_file.txt
  tests/test_files/apprise/invalid_multiple_urls.txt
  tests/test_files/apprise/invalid_single_url.txt
  tests/test_files/apprise/valid_multiple_urls.txt
  tests/test_files/apprise/valid_single_url.txt
Labels: bug, documentation, enhancement, ci/cd

#412 fix: log errors on startup
  .gitignore
  cyberdrop_dl/main.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/utils/constants.py
  cyberdrop_dl/utils/data_enums_classes/supported_domains.py
  cyberdrop_dl/utils/logger.py
  cyberdrop_dl/utils/utilities.py
  cyberdrop_dl/utils/yaml.py
  docs/reference/configuration-options/settings/runtime_options.md
Labels: bug, refactor
