Repository jbsparrow/CyberDropDownloader, pull requests merged in 2024-10, with the labels that each got.

#192 feat: rich logger
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/main.py
  cyberdrop_dl/managers/live_manager.py
  cyberdrop_dl/utils/utilities.py
Labels: enhancement

#193 refactor: simplify UI for v5.7
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/ui/progress/downloads_progress.py
  cyberdrop_dl/ui/progress/file_progress.py
  cyberdrop_dl/ui/progress/hash_progress.py
  cyberdrop_dl/ui/progress/sort_progress.py
  cyberdrop_dl/ui/progress/statistic_progress.py
Labels: enhancement

#194 docs: changelog and wiki updates for v5.7
  CHANGELOG.md
  docs/reference/configuration-options/settings.md
  pyproject.toml
Labels: enhancement

#201 Fix deleted cyberfile folder handling
  CHANGELOG.md
  cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py
Labels: bug

#202 docs: update supported sites
  README.md
  docs/reference/supported-websites.md
Labels: documentation

#205 fix: scraping on video playlists (tokyomotion)
  cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py
Labels: bug

#206 refactor: generate authentication info dynamically from config
  cyberdrop_dl/managers/manager.py
Labels: enhancement

#208 refactor: log downloads as "unsupported" for websites with no crawler
  CHANGELOG.md
  cyberdrop_dl/downloader/downloader.py
Labels: enhancement

#212 fix: remove console markdown from logs
  cyberdrop_dl/main.py
  cyberdrop_dl/utils/utilities.py
Labels: bug

#213 fix: bunkr file extension parsing
  cyberdrop_dl/utils/utilities.py
Labels: bug

#214 feat: add integration of Real Debrid
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/managers/real_debrid/__init__.py
  cyberdrop_dl/managers/real_debrid/api.py
  cyberdrop_dl/managers/real_debrid/errors.py
  cyberdrop_dl/managers/realdebrid_manager.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/realdebrid_crawler.py
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/utils/args/config_definitions.py
  cyberdrop_dl/utils/dataclasses/url_objects.py
  cyberdrop_dl/utils/utilities.py
Labels: enhancement

#220 fix: some 'unknown' errors
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/main.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/managers/live_manager.py
  cyberdrop_dl/managers/log_manager.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/managers/path_manager.py
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
  cyberdrop_dl/scraper/crawlers/celebforum_crawler.py
  cyberdrop_dl/scraper/crawlers/coomer_crawler.py
  cyberdrop_dl/scraper/crawlers/cyberdrop_crawler.py
  cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py
  cyberdrop_dl/scraper/crawlers/ehentai_crawler.py
  cyberdrop_dl/scraper/crawlers/erome_crawler.py
  cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
  cyberdrop_dl/scraper/crawlers/fapello_crawler.py
  cyberdrop_dl/scraper/crawlers/gofile_crawler.py
  cyberdrop_dl/scraper/crawlers/hotpic_crawler.py
  cyberdrop_dl/scraper/crawlers/imageban_crawler.py
  cyberdrop_dl/scraper/crawlers/imgbb_crawler.py
  cyberdrop_dl/scraper/crawlers/imgbox_crawler.py
  cyberdrop_dl/scraper/crawlers/imgkiwi_crawler.py
  cyberdrop_dl/scraper/crawlers/imgur_crawler.py
  cyberdrop_dl/scraper/crawlers/jpgchurch_crawler.py
  cyberdrop_dl/scraper/crawlers/kemono_crawler.py
  cyberdrop_dl/scraper/crawlers/leakedmodels_crawler.py
  cyberdrop_dl/scraper/crawlers/mediafire_crawler.py
  cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
  cyberdrop_dl/scraper/crawlers/nudostartv_crawler.py
  cyberdrop_dl/scraper/crawlers/omegascans_crawler.py
  cyberdrop_dl/scraper/crawlers/pimpandhost_crawler.py
  cyberdrop_dl/scraper/crawlers/pixeldrain_crawler.py
  cyberdrop_dl/scraper/crawlers/postimg_crawler.py
  cyberdrop_dl/scraper/crawlers/realbooru_crawler.py
  cyberdrop_dl/scraper/crawlers/reddit_crawler.py
  cyberdrop_dl/scraper/crawlers/redgifs_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34vault_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34xxx_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34xyz_crawler.py
  cyberdrop_dl/scraper/crawlers/saint_crawler.py
  cyberdrop_dl/scraper/crawlers/scrolller_crawler.py
  cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
  cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
  cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py
  cyberdrop_dl/scraper/crawlers/toonily_crawler.py
  cyberdrop_dl/scraper/crawlers/xbunker_crawler.py
  cyberdrop_dl/scraper/crawlers/xbunkr_crawler.py
  cyberdrop_dl/scraper/crawlers/xxxbunker_crawler.py
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/ui/progress/statistic_progress.py
  cyberdrop_dl/utils/args/config_definitions.py
  cyberdrop_dl/utils/utilities.py
  docs/reference/configuration-options/settings.md
Labels: bug

#217 refactor: switch to CSV for every log --- general logging fixes
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/main.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/managers/live_manager.py
  cyberdrop_dl/managers/log_manager.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/managers/path_manager.py
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
  cyberdrop_dl/scraper/crawlers/celebforum_crawler.py
  cyberdrop_dl/scraper/crawlers/coomer_crawler.py
  cyberdrop_dl/scraper/crawlers/cyberdrop_crawler.py
  cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py
  cyberdrop_dl/scraper/crawlers/ehentai_crawler.py
  cyberdrop_dl/scraper/crawlers/erome_crawler.py
  cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
  cyberdrop_dl/scraper/crawlers/fapello_crawler.py
  cyberdrop_dl/scraper/crawlers/gofile_crawler.py
  cyberdrop_dl/scraper/crawlers/hotpic_crawler.py
  cyberdrop_dl/scraper/crawlers/imageban_crawler.py
  cyberdrop_dl/scraper/crawlers/imgbb_crawler.py
  cyberdrop_dl/scraper/crawlers/imgbox_crawler.py
  cyberdrop_dl/scraper/crawlers/imgkiwi_crawler.py
  cyberdrop_dl/scraper/crawlers/imgur_crawler.py
  cyberdrop_dl/scraper/crawlers/jpgchurch_crawler.py
  cyberdrop_dl/scraper/crawlers/kemono_crawler.py
  cyberdrop_dl/scraper/crawlers/leakedmodels_crawler.py
  cyberdrop_dl/scraper/crawlers/mediafire_crawler.py
  cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
  cyberdrop_dl/scraper/crawlers/nudostartv_crawler.py
  cyberdrop_dl/scraper/crawlers/omegascans_crawler.py
  cyberdrop_dl/scraper/crawlers/pimpandhost_crawler.py
  cyberdrop_dl/scraper/crawlers/pixeldrain_crawler.py
  cyberdrop_dl/scraper/crawlers/postimg_crawler.py
  cyberdrop_dl/scraper/crawlers/realbooru_crawler.py
  cyberdrop_dl/scraper/crawlers/reddit_crawler.py
  cyberdrop_dl/scraper/crawlers/redgifs_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34vault_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34xxx_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34xyz_crawler.py
  cyberdrop_dl/scraper/crawlers/saint_crawler.py
  cyberdrop_dl/scraper/crawlers/scrolller_crawler.py
  cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
  cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
  cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py
  cyberdrop_dl/scraper/crawlers/toonily_crawler.py
  cyberdrop_dl/scraper/crawlers/xbunker_crawler.py
  cyberdrop_dl/scraper/crawlers/xbunkr_crawler.py
  cyberdrop_dl/scraper/crawlers/xxxbunker_crawler.py
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/ui/progress/statistic_progress.py
  cyberdrop_dl/utils/args/config_definitions.py
  cyberdrop_dl/utils/utilities.py
  docs/reference/configuration-options/settings.md
Labels: enhancement

#225 fix: initialize real_debrid before scrapers startup
  cyberdrop_dl/scraper/scraper.py
Labels: bug
