Repository jbsparrow/CyberDropDownloader, pull requests merged in 2024-11, with the labels that each got.

#230 feat: add support for % encoded URLs in input file
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/scraper/crawlers/cyberdrop_crawler.py
  cyberdrop_dl/scraper/scraper.py
Labels: enhancement

#229 fix: some wrong imports after reformat
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/scraper/crawlers/realdebrid_crawler.py
Labels: bug

#235 fix: only_host download filter
  cyberdrop_dl/clients/download_client.py
Labels: bug

#218 Add nekohouse.su support
  CHANGELOG.md
  README.md
  cyberdrop_dl/scraper/crawlers/kemono_crawler.py
  cyberdrop_dl/scraper/crawlers/nekohouse_crawler.py
  cyberdrop_dl/scraper/scraper.py
  docs/reference/supported-websites.md
Labels: enhancement

#238 cd: add release start scripts to repo
  .github/workflows/create_release.yaml
  scripts/release/start_linux.sh
  scripts/release/start_macOS.command
  scripts/release/start_windows.bat
Labels: enhancement

#241 feat: add support to limit the max number children while scraping
  CHANGELOG.md
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
  cyberdrop_dl/scraper/crawlers/celebforum_crawler.py
  cyberdrop_dl/scraper/crawlers/coomer_crawler.py
  cyberdrop_dl/scraper/crawlers/cyberdrop_crawler.py
  cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py
  cyberdrop_dl/scraper/crawlers/ehentai_crawler.py
  cyberdrop_dl/scraper/crawlers/erome_crawler.py
  cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
  cyberdrop_dl/scraper/crawlers/fapello_crawler.py
  cyberdrop_dl/scraper/crawlers/gofile_crawler.py
  cyberdrop_dl/scraper/crawlers/hotpic_crawler.py
  cyberdrop_dl/scraper/crawlers/imageban_crawler.py
  cyberdrop_dl/scraper/crawlers/imgbb_crawler.py
  cyberdrop_dl/scraper/crawlers/imgbox_crawler.py
  cyberdrop_dl/scraper/crawlers/imgur_crawler.py
  cyberdrop_dl/scraper/crawlers/kemono_crawler.py
  cyberdrop_dl/scraper/crawlers/leakedmodels_crawler.py
  cyberdrop_dl/scraper/crawlers/mediafire_crawler.py
  cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
  cyberdrop_dl/scraper/crawlers/omegascans_crawler.py
  cyberdrop_dl/scraper/crawlers/pimpandhost_crawler.py
  cyberdrop_dl/scraper/crawlers/pixeldrain_crawler.py
  cyberdrop_dl/scraper/crawlers/postimg_crawler.py
  cyberdrop_dl/scraper/crawlers/realbooru_crawler.py
  cyberdrop_dl/scraper/crawlers/reddit_crawler.py
  cyberdrop_dl/scraper/crawlers/redgifs_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34vault_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34xxx_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34xyz_crawler.py
  cyberdrop_dl/scraper/crawlers/scrolller_crawler.py
  cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
  cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
  cyberdrop_dl/scraper/crawlers/toonily_crawler.py
  cyberdrop_dl/scraper/crawlers/xbunker_crawler.py
  cyberdrop_dl/scraper/crawlers/xbunkr_crawler.py
  cyberdrop_dl/utils/args/args.py
  cyberdrop_dl/utils/args/config_definitions.py
  cyberdrop_dl/utils/dataclasses/url_objects.py
  docs/reference/cli-arguments.md
  docs/reference/configuration-options/settings.md
  docs/reference/notifications.md
  docs/reference/supported-websites.md
Labels: enhancement

#242 ci: upgrade CodeQL action to v3
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#245 fix: prepare files before looping through them (coomer/kemono)
  cyberdrop_dl/scraper/crawlers/coomer_crawler.py
  cyberdrop_dl/scraper/crawlers/kemono_crawler.py
Labels: bug

#239 ci: add ruff as linter and formatter + pre-commit hooks
  .github/workflows/ruff.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  poetry.lock
  pyproject.toml
Labels: enhancement

#262 fix: log origin of download errors
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/utils/dataclasses/url_objects.py
Labels: bug

#260 ci: update actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/create_release.yaml
  .github/workflows/publish-to-pypi.yaml
  .github/workflows/ruff.yaml
Labels: enhancement

#264 fix: csv logger
  cyberdrop_dl/managers/log_manager.py
Labels: bug

#265 fix: external links call from crawlers
  cyberdrop_dl/scraper/crawlers/celebforum_crawler.py
  cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
  cyberdrop_dl/scraper/crawlers/fapello_crawler.py
  cyberdrop_dl/scraper/crawlers/kemono_crawler.py
  cyberdrop_dl/scraper/crawlers/leakedmodels_crawler.py
  cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
  cyberdrop_dl/scraper/crawlers/pixeldrain_crawler.py
  cyberdrop_dl/scraper/crawlers/reddit_crawler.py
  cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
  cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
  cyberdrop_dl/scraper/crawlers/xbunker_crawler.py
Labels: bug

#263 fix: multiple running rich.live loops
  cyberdrop_dl/main.py
Labels: bug

#269 feat: import cookies from file (any supported site)
  cyberdrop_dl/managers/log_manager.py
  cyberdrop_dl/managers/path_manager.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/celebforum_crawler.py
  cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
  cyberdrop_dl/scraper/crawlers/leakedmodels_crawler.py
  cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
  cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
  cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
  cyberdrop_dl/scraper/crawlers/xbunker_crawler.py
Labels: enhancement

#266 refactor: better flaresolverr integration
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/managers/manager.py
Labels: enhancement

#283 Fix version check code
  cyberdrop_dl/utils/utilities.py
Labels: bug

#282 refactor: only log "download finished" if the download was successful
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/utils/utilities.py
Labels: refactor

#292 fix: config settings errors
  cyberdrop_dl/managers/args_manager.py
  cyberdrop_dl/managers/config_manager.py
  cyberdrop_dl/utils/args/args.py
Labels: bug

#291 fix: password protected files (cyberfile)
  cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py
Labels: bug

#297 refactor: move TUI user input options to a class
  cyberdrop_dl/clients/hash_client.py
  cyberdrop_dl/main.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/ui/program_ui.py
  cyberdrop_dl/ui/prompts/basic_prompts.py
  cyberdrop_dl/ui/prompts/continue_prompt.py
  cyberdrop_dl/ui/prompts/defaults.py
  cyberdrop_dl/ui/prompts/general_prompts.py
  cyberdrop_dl/ui/prompts/settings_authentication_prompts.py
  cyberdrop_dl/ui/prompts/settings_global_prompts.py
  cyberdrop_dl/ui/prompts/settings_hash_prompts.py
  cyberdrop_dl/ui/prompts/settings_user_prompts.py
  cyberdrop_dl/ui/prompts/url_file_prompts.py
  cyberdrop_dl/ui/prompts/user_prompts.py
  cyberdrop_dl/ui/ui.py
  cyberdrop_dl/utils/args/browser_cookie_extraction.py
  cyberdrop_dl/utils/args/config_definitions.py
  cyberdrop_dl/utils/constants.py
  cyberdrop_dl/utils/cookie_extraction.py
  cyberdrop_dl/utils/logger.py
  cyberdrop_dl/utils/sorting.py
  cyberdrop_dl/utils/transfer/transfer_v4_config.py
  cyberdrop_dl/utils/utilities.py
Labels: refactor

#301 fix: chevereto CDN regex
  cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
  cyberdrop_dl/ui/prompts/user_prompts.py
Labels: bug

#304 refactor: move skip_host/only_host check up in the logic
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/scraper/crawler.py
Labels: refactor

#309 fix: open config files when running without DE (linux)
  cyberdrop_dl/utils/utilities.py
Labels: bug

#308 fix: do not run update_last_forum_post if input_file is html
  cyberdrop_dl/managers/log_manager.py
Labels: bug

#312 fix: do not startup real_debrid unless enabled
  cyberdrop_dl/managers/realdebrid_manager.py
Labels: bug

#315 refactor: add proper integration of crawlers that support multiple sites/domains
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
  cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
  cyberdrop_dl/scraper/crawlers/reddit_crawler.py
  cyberdrop_dl/scraper/scraper.py
Labels: refactor

#318 ci: update ruff action
  .github/workflows/ruff.yaml
  cyberdrop_dl/clients/hash_client.py
  cyberdrop_dl/main.py
  cyberdrop_dl/scraper/filters.py
  cyberdrop_dl/utils/data_enums_classes/hash.py
  cyberdrop_dl/utils/database/tables/hash_table.py
  poetry.lock
  pyproject.toml
Labels: chore

#327 fix: update bunkr crawler to handle uuid filenames
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
Labels: bug

#330 fix: database transfer error
  cyberdrop_dl/utils/database/tables/hash_table.py
Labels: bug

#333 fix: restrict sites in config browser cookies settings
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/ui/prompts/user_prompts.py
  cyberdrop_dl/utils/cookie_extraction.py
  cyberdrop_dl/utils/data_enums_classes/supported_domains.py
  poetry.lock
  pyproject.toml
Labels: bug

#338 fix: add content type overrides to download special extensions
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/utils/constants.py
Labels: bug

#339 fix: don't dedupe on ignore
  cyberdrop_dl/clients/hash_client.py
Labels: bug

#335 fix: downloads reaching eof at 0 bytes
  cyberdrop_dl/managers/client_manager.py
Labels: bug
