Repository jbsparrow/CyberDropDownloader, pull requests merged in 2025-03, with the labels that each got.

#734 ci/cd: update tests
  .github/workflows/ci.yml
  cyberdrop_dl/utils/apprise.py
  tests/test_apprise.py
Labels: refactor, ci/cd

#736 fix: flaresolverr integration
  cyberdrop_dl/managers/client_manager.py
Labels: bug

#742 fix: invalid URL handle (xenforo)
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
Labels: bug

#737 fix: 403 on some files (bunkr)
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
Labels: bug

#738 refactor: allow writing not ascii chars (`--dump-json`)
  cyberdrop_dl/main.py
  cyberdrop_dl/utils/dumper.py
Labels: refactor

#740 ci/cd: use version number for release titles
  .github/workflows/create_release.yaml
Labels: ci/cd

#747 test: fix poetry install on Windows
  .github/workflows/ci.yml
Labels: ci/cd

#739 ci/cd: fix windows startup script
  scripts/release/start_windows.bat
Labels: ci/cd

#744 fix: get URL from encrypted link (update) (jpg5)
  cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
Labels: bug

#741 perf: use generators for input item URLs
  cyberdrop_dl/scraper/scraper.py
Labels: refactor

#749 feat: add OneDrive support
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/onedrive_crawler.py
Labels: new website

#750 fix: update download api (bunkr)
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
Labels: bug

#751 Add crawler for sex.com
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/sex_dot_com_crawler.py
Labels: new website

#765 fix: handle deleted videos (eporner)
  cyberdrop_dl/scraper/crawlers/eporner_crawler.py
Labels: bug

#759 feat: disable cache
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/managers/cache_manager.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/scraper/crawlers/reddit_crawler.py
  cyberdrop_dl/scraper/filters.py
  cyberdrop_dl/utils/args.py
  cyberdrop_dl/utils/constants.py
  docs/reference/cli-arguments.md
Labels: enhancement

#760 refactor: log requests cache activity
  cyberdrop_dl/main.py
  cyberdrop_dl/utils/logger.py
Labels: refactor

#778 fix: jsonl timestamp serializer
  cyberdrop_dl/utils/dumper.py
Labels: bug

#777 fix: slow downloads from bunkr
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
Labels: bug

#779 fix: sex.com URL parsing
  cyberdrop_dl/scraper/crawlers/sex_dot_com_crawler.py
Labels: bug

#781 fix: handle invalid URLs (google drive)
  cyberdrop_dl/scraper/crawlers/google_drive_crawler.py
Labels: bug

#782 refactor: reduce rate limit (jpg5)
  cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
Labels: refactor

#788 docs: add install instructions for Android (wiki)
  docs/SUMMARY.md
  docs/getting-started/cyberdrop-dl-on-android.md
Labels: documentation

#792 fix: handle paths with special characters (stats hyperlinks)
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/utils/logger.py
Labels: bug

#789 refactor: revalidate config after the user edits it from the UI
  cyberdrop_dl/ui/program_ui.py
  cyberdrop_dl/utils/utilities.py
Labels: refactor

#790 docs: update CLI overview (wiki)
  docs/reference/cli-arguments.md
Labels: documentation

#786 fix: slows downloads (bunkr)(2)
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
Labels: bug

#764 feat: add custom `get_soup` method with `curl_cffi`
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/scraper/crawlers/spankbang_crawler.py
  cyberdrop_dl/utils/javascript.py
  poetry.lock
  pyproject.toml
Labels: bug, enhancement, refactor

#793 fix: DDoSGuard check from pages with no title
  cyberdrop_dl/managers/client_manager.py
Labels: bug

#787 feat: add support for SharePoint backend links (OneDrive)
  cyberdrop_dl/scraper/crawlers/onedrive_crawler.py
Labels: enhancement

#684 feat: replace `no_crawler` with a generic crawler to download from unsupported sites
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/generic_crawler.py
  cyberdrop_dl/scraper/scraper.py
Labels: enhancement

#797 refactor: log dicts as json by default
  cyberdrop_dl/utils/logger.py
Labels: refactor

#796 fix: remove console markup from webhook
  cyberdrop_dl/utils/constants.py
  cyberdrop_dl/utils/utilities.py
Labels: bug

#785 fix: handle single file share links (yandex)
  cyberdrop_dl/scraper/crawlers/yandex_disk_crawler.py
Labels: bug

#794 fix: tag and category support (dirtyship)
  cyberdrop_dl/scraper/crawlers/dirtyship_crawler.py
Labels: bug

#802 feat: add doodstream support
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/doodstream_crawler.py
  poetry.lock
Labels: new website

#795 fix: download profiles with 1k+ posts (redgifs)
  cyberdrop_dl/scraper/crawlers/redgifs_crawler.py
Labels: bug

#806 feat: add send.now support
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/send_now_crawler.py
Labels: new website

#805 feat: add catbox and litterbox support
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/catbox_crawler.py
Labels: new website

#801 ci/cd: add new site request issue template
  .github/ISSUE_TEMPLATE/new_site_request.yml
Labels: ci/cd

#803 feat: add bestprettygirl support
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/bestprettygirl_crawler.py
Labels: new website

#799 feature: Add crawler for pmvhaven.com
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/pmvhaven_crawler.py
  cyberdrop_dl/utils/utilities.py
Labels: new website

#800 feat: add motherless support
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/motherless_crawler.py
Labels: new website

#811 ci/cd: fix new site issue template
  .github/ISSUE_TEMPLATE/new_site_request.yml
Labels: ci/cd

#810 fix: bestprettygirl crawler
  cyberdrop_dl/scraper/crawlers/bestprettygirl_crawler.py
Labels: bug

#813 refactor: make downloader return success
  cyberdrop_dl/downloader/downloader.py
Labels: refactor

#816 docs: update changelog
  CHANGELOG.md
Labels: documentation

#817 refactor: warn about expired cookie files
  cyberdrop_dl/managers/client_manager.py
Labels: refactor

#819 fix: profiling logs file copy
  cyberdrop_dl/profiling.py
  cyberdrop_dl/utils/constants.py
Labels: bug

#820 refactor: add graceful shutdown
  cyberdrop_dl/main.py
Labels: refactor

#818 perf: queue logging to prevent blocking the async loop
  cyberdrop_dl/main.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/utils/constants.py
  cyberdrop_dl/utils/logger.py
Labels: refactor

#815 refactor: move `parse_url` to utils
  cyberdrop_dl/config_definitions/custom/converters.py
  cyberdrop_dl/config_definitions/custom/types.py
  cyberdrop_dl/crawlers/crawler.py
  cyberdrop_dl/crawlers/xenforo/xenforo.py
  cyberdrop_dl/scraper/filters.py
  cyberdrop_dl/scraper/scrape_mapper.py
  cyberdrop_dl/utils/utilities.py
Labels: refactor

#823 perf: async delete files (dedupe)
  cyberdrop_dl/clients/hash_client.py
Labels: refactor

#831 fix: concurrent free space check
  cyberdrop_dl/clients/download_client.py
Labels: bug

#834 refactor: fallback to `Last-Modified` for file date
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/crawlers/google_drive.py
Labels: refactor

#830 refactor: try to download images from any URL (twimg)
  cyberdrop_dl/crawlers/twitter_images.py
Labels: refactor

#829 feat: save scraped pages as html
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/managers/path_manager.py
  cyberdrop_dl/utils/constants.py
  cyberdrop_dl/utils/utilities.py
Labels: enhancement

#836 refactor: use portrait by default when running in termux
  cyberdrop_dl/env.py
  cyberdrop_dl/utils/args.py
Labels: refactor

#798 feat: add xhamster support
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/crawler.py
  cyberdrop_dl/crawlers/xhamster.py
  cyberdrop_dl/utils/javascript.py
  cyberdrop_dl/utils/utilities.py
Labels: new website

#842 refactor: disable textual UI
  cyberdrop_dl/managers/live_manager.py
Labels: refactor

#841 fix: catch errors on `curl_cffi` import
  cyberdrop_dl/clients/scraper_client.py
Labels: bug
