Repository jbsparrow/CyberDropDownloader, pull requests merged in 2025-04, with the labels that each got.

#840 perf: use async loop to keep track of available space
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/config_definitions/global_settings.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/managers/download_manager.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/managers/storage_manager.py
  cyberdrop_dl/ui/progress/file_progress.py
  cyberdrop_dl/ui/textual.py
  cyberdrop_dl/utils/args.py
  poetry.lock
  pyproject.toml
Labels: enhancement, refactor

#838 docs: wiki and changelog updates for v6.8.0 release
  CHANGELOG.md
  docs/reference/cli-arguments.md
  docs/reference/configuration-options/global-settings/general.md
  docs/reference/configuration-options/settings/files.md
  docs/reference/supported-websites.md
  poetry.lock
  pyproject.toml
Labels: documentation, chore

#852 fix: request response / curl references
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/managers/client_manager.py
Labels: bug

#851 fix: always deep scrape albums (bunkr)
  cyberdrop_dl/crawlers/bunkrr.py
Labels: bug

#855 feat: add profile support (eporner)
  cyberdrop_dl/crawlers/eporner.py
Labels: enhancement

#812 feat: add hls (m3u8) support
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/clients/hash_client.py
  cyberdrop_dl/crawlers/crawler.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/managers/path_manager.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
  cyberdrop_dl/utils/database/tables/history_table.py
  cyberdrop_dl/utils/ffmpeg.py
  cyberdrop_dl/utils/utilities.py
Labels: enhancement

#849 feat: add ashemaletube support
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/ashemaletube.py
Labels: new website

#859 fix: embed parsing (xenforo)
  cyberdrop_dl/crawlers/xenforo/xenforo.py
Labels: bug

#861 fix: get soup from non curl responses
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/utils/utilities.py
Labels: bug

#807 feat: add missav support
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/missav.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/utils/ffmpeg.py
  cyberdrop_dl/utils/utilities.py
Labels: enhancement, refactor, new website

#863 feat: add thisvid support
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/thisvid.py
Labels: new website

#867 fix: free space check when using network drives (windows)
  cyberdrop_dl/managers/download_manager.py
  cyberdrop_dl/managers/storage_manager.py
Labels: bug

#881 fix: [ashemaletube] site's models category changed to pornstars or creators
  cyberdrop_dl/crawlers/ashemaletube.py
Labels: bug

#882 fix: use canonical URL for videos (thisvid)
  cyberdrop_dl/crawlers/thisvid.py
Labels: bug

#879 fix: downloader stalling and creating empty files
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/crawler.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
  cyberdrop_dl/utils/utilities.py
Labels: bug, refactor

#880 refactor: mock manager
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/managers/mock_manager.py
  cyberdrop_dl/scraper/scrape_mapper.py
Labels: refactor

#884 fix: use the canonical URL as the database entry (tiktok)
  cyberdrop_dl/crawlers/tiktok.py
Labels: bug

#883 feat: add jitter inbetween downloads
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/config_definitions/global_settings.py
  cyberdrop_dl/downloader/downloader.py
Labels: enhancement

#891 bug: [ashemaletube] fixing json parsing
  cyberdrop_dl/crawlers/ashemaletube.py
Labels: bug

#894 refactor: make the base crawler parse all dates
  cyberdrop_dl/crawlers/crawler.py
Labels: refactor

#887 perf: extract cookies once per browser
  cyberdrop_dl/utils/cookie_management.py
Labels: refactor

#896 refactor: move director out of main.py
  cyberdrop_dl/director.py
  cyberdrop_dl/main.py
Labels: refactor

#902 sync: merge fix `task_id` to release v6.9.0
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
Labels: chore

#876 feat: add support to noodlemagazine
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/noodle_magazine.py
  cyberdrop_dl/managers/download_manager.py
Labels: new website

#890 chore: release v6.9.0
  CHANGELOG.md
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/clients/hash_client.py
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/ashemaletube.py
  cyberdrop_dl/crawlers/bunkrr.py
  cyberdrop_dl/crawlers/crawler.py
  cyberdrop_dl/crawlers/eporner.py
  cyberdrop_dl/crawlers/missav.py
  cyberdrop_dl/crawlers/thisvid.py
  cyberdrop_dl/crawlers/tiktok.py
  cyberdrop_dl/crawlers/xenforo/titsintops.py
  cyberdrop_dl/crawlers/xenforo/xenforo.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/managers/download_manager.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/managers/mock_manager.py
  cyberdrop_dl/managers/path_manager.py
  cyberdrop_dl/managers/storage_manager.py
  cyberdrop_dl/scraper/scrape_mapper.py
  cyberdrop_dl/ui/prompts/user_prompts.py
  cyberdrop_dl/utils/args.py
  cyberdrop_dl/utils/data_enums_classes/supported_domains.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
  cyberdrop_dl/utils/database/tables/history_table.py
  cyberdrop_dl/utils/ffmpeg.py
  cyberdrop_dl/utils/utilities.py
  docs/reference/cli-arguments.md
  docs/reference/supported-websites.md
  pyproject.toml
Labels: chore

#911 fix: better handling of missing ffmpeg
  CHANGELOG.md
  cyberdrop_dl/utils/ffmpeg.py
  pyproject.toml
Labels: bug

#903 fix: wrong exit codes
  cyberdrop_dl/director.py
Labels: bug

#904 refactor: handle keyboard interrupts while still importing modules
  cyberdrop_dl/main.py
Labels: refactor

#924 fix: crawler fixes (erome)
  cyberdrop_dl/crawlers/erome.py
Labels: bug, refactor

#920 fix: crawler fixes (ehentai)
  cyberdrop_dl/crawlers/ehentai.py
Labels: bug, refactor

#915 fix: crawler fixes (bestprettygirls)
  cyberdrop_dl/crawlers/bestprettygirl.py
Labels: bug, refactor

#916 refactor: do not use get for expected values (bunkr_albums)
  cyberdrop_dl/crawlers/bunkrr_albums_io.py
Labels: refactor

#925 feat: add date extraction (rule34xxx)
  cyberdrop_dl/crawlers/rule34xxx.py
Labels: enhancement, refactor

#914 fix: crawler fixes (ashemaletube)
  cyberdrop_dl/crawlers/ashemaletube.py
Labels: bug, refactor

#913 fix: iter items on chevereto profiles
  cyberdrop_dl/crawlers/chevereto.py
Labels: bug

#922 fix: crawler fixes (rule34xyz , rule34vault)
  cyberdrop_dl/crawlers/rule34vault.py
  cyberdrop_dl/crawlers/rule34xyz.py
Labels: bug, refactor

#926 chore: sync master to dev
  CHANGELOG.md
  cyberdrop_dl/utils/ffmpeg.py
  pyproject.toml
Labels: chore

#906 refactor: prioritize real debrid and jdownloader over generic crawler
  cyberdrop_dl/scraper/scrape_mapper.py
Labels: refactor

#910 refactor: let crawlers define their own cache filter
  cyberdrop_dl/crawlers/coomer.py
  cyberdrop_dl/crawlers/crawler.py
  cyberdrop_dl/crawlers/kemono.py
  cyberdrop_dl/crawlers/xenforo/xenforo.py
  cyberdrop_dl/managers/cache_manager.py
  cyberdrop_dl/scraper/filters.py
Labels: refactor

#912 test: add startup tests
  tests/test_startup.py
Labels: ci/cd

#917 refactor: split cyberfile and iceyfile crawlers
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/cyberfile.py
  cyberdrop_dl/crawlers/iceyfile.py
Labels: refactor

#918 refactor: use new syntax (doodstream)
  cyberdrop_dl/crawlers/doodstream.py
Labels: refactor

#919 refactor: use self methods (e621)
  cyberdrop_dl/crawlers/e621.py
Labels: refactor

#934 fix: No file extension from og filename (bunkr)
  cyberdrop_dl/crawlers/bunkrr.py
Labels: bug

#921 refactor: use new syntax (eporner)
  cyberdrop_dl/crawlers/eporner.py
Labels: refactor

#923 refactor: use new syntax (cyberdrop)
  cyberdrop_dl/crawlers/cyberdrop.py
Labels: refactor

#930 fix: get filename from og properties (bunkr)
  cyberdrop_dl/crawlers/bunkrr.py
Labels: bug

#941 feat: add files.vc support
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/files_vc.py
Labels: new website

#943 fix: update download URL (GoogleDrive)
  cyberdrop_dl/crawlers/google_drive.py
Labels: bug

#945 fix: ignore errors while getting available mountpoints
  cyberdrop_dl/managers/storage_manager.py
Labels: bug

#927 feat: add Mixdrop + archivebate support
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/archivebate.py
  cyberdrop_dl/crawlers/mixdrop.py
Labels: new website

#948 perf: use a single, global session for the entire run
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/scraper/scrape_mapper.py
Labels: refactor

#907 feat: allow the user to disable the generic crawler
  cyberdrop_dl/config_definitions/global_settings.py
  cyberdrop_dl/scraper/scrape_mapper.py
Labels: enhancement

#944 refactor: update supported domains (doodstream)
  cyberdrop_dl/crawlers/doodstream.py
Labels: refactor

#946 style: fix signature of functions that use wrappers
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/crawlers/crawler.py
  cyberdrop_dl/crawlers/generic.py
  cyberdrop_dl/director.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/scraper/jdownloader.py
  cyberdrop_dl/ui/program_ui.py
  cyberdrop_dl/utils/cookie_management.py
  cyberdrop_dl/utils/utilities.py
Labels: refactor

#898 refactor: switch to inheritance for chevereto sites
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/_chevereto.py
  cyberdrop_dl/crawlers/chevereto.py
  cyberdrop_dl/crawlers/imagepond.py
  cyberdrop_dl/crawlers/jpg5.py
Labels: refactor

#886 feat: auto switch primary host (bunkr)
  cyberdrop_dl/crawlers/bunkrr.py
Labels: enhancement

#895 refactor: generalize kemono crawler and make coomer and nekohouse inherit from it
  cyberdrop_dl/config_definitions/authentication_settings.py
  cyberdrop_dl/crawlers/coomer.py
  cyberdrop_dl/crawlers/crawler.py
  cyberdrop_dl/crawlers/kemono.py
  cyberdrop_dl/crawlers/nekohouse.py
  cyberdrop_dl/utils/utilities.py
  docs/reference/supported-websites.md
Labels: refactor

#949 fix: handling videos with unknown resolution (Thisvid)
  cyberdrop_dl/crawlers/thisvid.py
Labels: bug

#897 feat: add pkmncards.com support
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/pkmncards.py
Labels: new website

#951 perf: make all file system calls async
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/clients/hash_client.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/managers/log_manager.py
  cyberdrop_dl/scraper/scrape_mapper.py
  cyberdrop_dl/utils/sorting.py
  cyberdrop_dl/utils/utilities.py
Labels: refactor

#953 perf: make setting file dates async
  cyberdrop_dl/downloader/downloader.py
  poetry.lock
  pyproject.toml
Labels: refactor

#937 feat: add (native) mega.nz support
  cyberdrop_dl/config_definitions/authentication_settings.py
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/mega_nz.py
  cyberdrop_dl/downloader/mega_nz.py
  cyberdrop_dl/licenses/LICENSE-APACHE
Labels: new website

#956 feat: add support to albums (ThisVid)
  cyberdrop_dl/crawlers/thisvid.py
Labels: enhancement

#936 feat: add support to porntrex
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/crawler.py
  cyberdrop_dl/crawlers/porntrex.py
Labels: new website

#960 fix: remove call to missing method add_separate_post_title (xenforo)
  cyberdrop_dl/crawlers/xenforo/xenforo.py
Labels: bug
