Repository jbsparrow/CyberDropDownloader, pull requests merged in 2025-01, with the labels that each got.

#422 fix: e-hentai crawler
  cyberdrop_dl/scraper/crawlers/ehentai_crawler.py
Labels: bug

#418 ci/cd: update workflows, ruff rules and pre-commit hooks
  .github/workflows/ruff.yaml
  .pre-commit-config.yaml
  pyproject.toml
Labels: chore, ci/cd

#416 docs: wiki and changelog updates for v6.1.0 release
  CHANGELOG.md
  README.md
  docs/reference/cli-arguments.md
  docs/transition-to-v6.md
  pyproject.toml
Labels: documentation

#407 hash-db-error-fix
  .gitignore
  cyberdrop_dl/utils/transfer/transfer_hash_db.py
Labels: bug

#429 fix: do not try to transfer `downloader.log` (v4 import)
  cyberdrop_dl/utils/transfer/db_setup.py
Labels: bug

#425 perf: remove crawler scrape lock
  cyberdrop_dl/scraper/crawler.py
Labels: refactor

#430 chore: upgrade to poetry 2.0
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: chore

#428 fix: general crawler fixes
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/managers/real_debrid/api.py
  cyberdrop_dl/managers/real_debrid/errors.py
  cyberdrop_dl/managers/realdebrid_manager.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
  cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
  cyberdrop_dl/scraper/crawlers/cyberdrop_crawler.py
  cyberdrop_dl/scraper/crawlers/gofile_crawler.py
  cyberdrop_dl/scraper/crawlers/imgbox_crawler.py
  cyberdrop_dl/scraper/crawlers/imgur_crawler.py
  cyberdrop_dl/scraper/crawlers/mediafire_crawler.py
  cyberdrop_dl/scraper/crawlers/omegascans_crawler.py
  cyberdrop_dl/scraper/crawlers/reddit_crawler.py
  cyberdrop_dl/scraper/crawlers/saint_crawler.py
  cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py
  cyberdrop_dl/scraper/crawlers/xxxbunker_crawler.py
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/utils/constants.py
  cyberdrop_dl/utils/utilities.py
  cyberdrop_dl/utils/yaml.py
Labels: bug, refactor

#431 perf: improve hashing
  cyberdrop_dl/clients/hash_client.py
Labels: refactor

#438 Feature: Add allporncomix crawler
  cyberdrop_dl/config_definitions/authentication_settings.py
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/allporncomix_crawler.py
  cyberdrop_dl/scraper/filters.py
Labels: enhancement

#437 fix: hashing
  cyberdrop_dl/managers/path_manager.py
Labels: bug

#440 Feature: Add support for bellazon.com
  cyberdrop_dl/config_definitions/authentication_settings.py
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/allporncomix_crawler.py
  cyberdrop_dl/scraper/crawlers/bellazon_crawler.py
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
Labels: enhancement

#446 fix: delete startup log file if empty
  cyberdrop_dl/main.py
Labels: bug

#447 refactor: use canonical URLs (chevereto)
  cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
Labels: refactor

#442 fix: make `MediaItem` hashable
  cyberdrop_dl/clients/hash_client.py
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
Labels: bug

#448 feat: add videos support (chevereto)
  cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
Labels: enhancement

#454 Feature: Add Tits In Tops Crawler
  cyberdrop_dl/config_definitions/authentication_settings.py
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/titsintops_crawler.py
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
  cyberdrop_dl/scraper/filters.py
Labels: enhancement

#455 Fix: Windows Startup Logger Permission Error
  cyberdrop_dl/main.py
  cyberdrop_dl/utils/yaml.py
Labels: bug

#457 feat: add support for filesystem URLs (pixeldrain)
  cyberdrop_dl/scraper/crawlers/pixeldrain_crawler.py
Labels: enhancement

#452 fix: pre-setup crawlers before making any request (GoFile, Xenforo)
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/gofile_crawler.py
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
  cyberdrop_dl/scraper/jdownloader.py
  cyberdrop_dl/scraper/scraper.py
Labels: bug

#459 feat: add support indirect links (routed via api) (saint)
  cyberdrop_dl/scraper/crawlers/saint_crawler.py
Labels: enhancement

#460 fix: DDoS-Guard check
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
Labels: bug

#461 docs: wiki and changelog updates for v6.2.0 release
  CHANGELOG.md
  docs/reference/supported-websites.md
  pyproject.toml
Labels: documentation, chore

#468 fix: handle bunkr reinforced links
  CHANGELOG.md
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
Labels: bug

#472 fix: update jpg5 rate limit
  cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
Labels: bug

#473 feat: handle direct links from forums (attachments)
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
Labels: enhancement

#475 fix: handle encoded URLs from within any crawler
  CHANGELOG.md
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/config_definitions/global_settings.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
  cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
  cyberdrop_dl/scraper/crawlers/coomer_crawler.py
  cyberdrop_dl/scraper/crawlers/cyberdrop_crawler.py
  cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py
  cyberdrop_dl/scraper/crawlers/ehentai_crawler.py
  cyberdrop_dl/scraper/crawlers/erome_crawler.py
  cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
  cyberdrop_dl/scraper/crawlers/fapello_crawler.py
  cyberdrop_dl/scraper/crawlers/gofile_crawler.py
  cyberdrop_dl/scraper/crawlers/hotpic_crawler.py
  cyberdrop_dl/scraper/crawlers/imageban_crawler.py
  cyberdrop_dl/scraper/crawlers/imgbb_crawler.py
  cyberdrop_dl/scraper/crawlers/imgbox_crawler.py
  cyberdrop_dl/scraper/crawlers/imgur_crawler.py
  cyberdrop_dl/scraper/crawlers/kemono_crawler.py
  cyberdrop_dl/scraper/crawlers/mediafire_crawler.py
  cyberdrop_dl/scraper/crawlers/nekohouse_crawler.py
  cyberdrop_dl/scraper/crawlers/nudostartv_crawler.py
  cyberdrop_dl/scraper/crawlers/omegascans_crawler.py
  cyberdrop_dl/scraper/crawlers/pimpandhost_crawler.py
  cyberdrop_dl/scraper/crawlers/pixeldrain_crawler.py
  cyberdrop_dl/scraper/crawlers/pixhost_crawler.py
  cyberdrop_dl/scraper/crawlers/postimg_crawler.py
  cyberdrop_dl/scraper/crawlers/realbooru_crawler.py
  cyberdrop_dl/scraper/crawlers/realdebrid_crawler.py
  cyberdrop_dl/scraper/crawlers/reddit_crawler.py
  cyberdrop_dl/scraper/crawlers/redgifs_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34vault_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34xxx_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34xyz_crawler.py
  cyberdrop_dl/scraper/crawlers/saint_crawler.py
  cyberdrop_dl/scraper/crawlers/scrolller_crawler.py
  cyberdrop_dl/scraper/crawlers/titsintops_crawler.py
  cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py
  cyberdrop_dl/scraper/crawlers/toonily_crawler.py
  cyberdrop_dl/scraper/crawlers/xbunker_crawler.py
  cyberdrop_dl/scraper/crawlers/xbunkr_crawler.py
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
  cyberdrop_dl/scraper/crawlers/xxxbunker_crawler.py
  cyberdrop_dl/utils/database/tables/history_table.py
Labels: bug, refactor

#478 test: profiling
  .gitignore
  CHANGELOG.md
  cyberdrop_dl/main.py
  cyberdrop_dl/scraper/crawlers/ehentai_crawler.py
  cyberdrop_dl/scraper/crawlers/luscious_crawler.py
  cyberdrop_dl/scraper/crawlers/realbooru_crawler.py
  cyberdrop_dl/scraper/crawlers/saint_crawler.py
  cyberdrop_dl/scraper/crawlers/xxxbunker_crawler.py
  poetry.lock
  pyproject.toml
Labels: refactor

#495 refactor: override min required free space on startup
  cyberdrop_dl/config_definitions/global_settings.py
  cyberdrop_dl/utils/transfer/transfer_v4_config.py
Labels: refactor

#490 feat: add sendvid.com support
  CHANGELOG.md
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/sendvid_crawler.py
  docs/reference/supported-websites.md
Labels: enhancement

#492 fix: imgur crawler
  CHANGELOG.md
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/scraper/crawlers/imgur_crawler.py
  docs/reference/supported-websites.md
Labels: bug, enhancement

#493 fix: mediafire crawler
  cyberdrop_dl/scraper/crawlers/mediafire_crawler.py
Labels: bug

#494 fix: update stream redirects (bunkr)
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
Labels: bug

#432 perf: use deque for file, scrape and sort progress
  cyberdrop_dl/clients/hash_client.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/main.py
  cyberdrop_dl/managers/live_manager.py
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/ui/progress/deque_progress.py
  cyberdrop_dl/ui/progress/file_progress.py
  cyberdrop_dl/ui/progress/hash_progress.py
  cyberdrop_dl/ui/progress/scraping_progress.py
  cyberdrop_dl/ui/progress/sort_progress.py
  cyberdrop_dl/utils/sorting.py
Labels: refactor

#484 docs: wiki and changelog updates for v6.3.0 release
  CHANGELOG.md
  docs/reference/supported-websites.md
  poetry.lock
  pyproject.toml
Labels: documentation, chore

#487 feat: add support for bunkr-albums.io
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/bunkrr_albums_io_crawler.py
Labels: enhancement

#486 fix: regression - additive config options
  cyberdrop_dl/managers/manager.py
  docs/reference/configuration-options/settings/ignore_options.md
Labels: bug

#510 fix: do not use startup logger on keyboard interupt
  cyberdrop_dl/main.py
Labels: bug

#508 fix: db chevereto domains conflicts
  cyberdrop_dl/utils/database/tables/history_table.py
Labels: bug

#456 refactor: add `MediaItem` inmediatly to db
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/downloader/downloader.py
Labels: refactor

#496 feat: skip slow downloads
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/managers/real_debrid/api.py
  cyberdrop_dl/ui/progress/file_progress.py
  cyberdrop_dl/utils/utilities.py
  docs/reference/configuration-options/global-settings/rate-limiting-options.md
  docs/reference/configuration-options/settings/runtime_options.md
Labels: enhancement

#515 fix: imgbb crawler
  cyberdrop_dl/scraper/crawlers/imgbb_crawler.py
Labels: bug

#513 fix: imagebam crawler
  CHANGELOG.md
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/imagebam_crawler.py
  cyberdrop_dl/scraper/crawlers/imageban_crawler.py
  docs/reference/supported-websites.md
Labels: bug

#512 feat: add twitter images (twimg) support
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/twitter_images_crawler.py
Labels: enhancement

#509 fix: Tokyomotion fixes
  cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py
Labels: bug

#518 Feature: Add TikTok Crawler
  CHANGELOG.md
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/tiktok_crawler.py
  cyberdrop_dl/utils/args.py
  docs/reference/cli-arguments.md
  docs/reference/supported-websites.md
Labels: enhancement

#517 fix: xenforo crawlers
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/allporncomix_crawler.py
  cyberdrop_dl/scraper/crawlers/bellazon_crawler.py
  cyberdrop_dl/scraper/crawlers/coomer_crawler.py
  cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
  cyberdrop_dl/scraper/crawlers/gofile_crawler.py
  cyberdrop_dl/scraper/crawlers/imagebam_crawler.py
  cyberdrop_dl/scraper/crawlers/imgur_crawler.py
  cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
  cyberdrop_dl/scraper/crawlers/realbooru_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34xxx_crawler.py
  cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
  cyberdrop_dl/scraper/crawlers/titsintops_crawler.py
  cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py
  cyberdrop_dl/scraper/crawlers/xbunker_crawler.py
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
  cyberdrop_dl/scraper/crawlers/xxxbunker_crawler.py
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
Labels: bug, refactor

#514 feat: add pornpics support
  CHANGELOG.md
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/pornpics_crawler.py
  docs/reference/supported-websites.md
Labels: New Website

#528 refactor: create base class for download and scrape failures + reformat stats
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/ui/progress/deque_progress.py
  cyberdrop_dl/ui/progress/downloads_progress.py
  cyberdrop_dl/ui/progress/hash_progress.py
  cyberdrop_dl/ui/progress/statistic_progress.py
Labels: refactor

#531 fix: delete invalid database rows on startup
  cyberdrop_dl/managers/db_manager.py
  cyberdrop_dl/utils/database/tables/history_table.py
Labels: bug

#540 fix: prettify errors
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/ui/progress/statistic_progress.py
Labels: bug

#521 Feature: Add comics.8muses.com crawler
  CHANGELOG.md
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/eightmuses_crawler.py
  docs/reference/supported-websites.md
Labels: New Website

#547 Fix error code logging system
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/ui/progress/statistic_progress.py
Labels: bug

#548 fix: attachments downloads + `NoExtensionError` handling (xenforo)
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
Labels: bug

#533 docs: wiki and changelog updates for v6.4.0 release
  CHANGELOG.md
  docs/SUMMARY.md
  docs/reference/configuration-options/settings/ignore_options.md
  docs/reference/configuration-options/settings/runtime_options.md
  docs/reference/configuration-options/special_setting_types.md
  pyproject.toml
Labels: documentation, chore

#527 refactor: add back `browser_cookie3` as an external dependency
  CHANGELOG.md
  cyberdrop_dl/dependencies/browser_cookie3/__init__.py
  cyberdrop_dl/main.py
  cyberdrop_dl/ui/program_ui.py
  cyberdrop_dl/utils/cookie_management.py
  docs/reference/configuration-options/settings/browser_cookies.md
  poetry.lock
  pyproject.toml
Labels: refactor, chore

#511 feat: add support for iceyfile.com
  CHANGELOG.md
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py
  docs/reference/supported-websites.md
Labels: New Website
