Repository jbsparrow/CyberDropDownloader, pull requests merged in 2025-05, with the labels that each got.

#963 refactor: update CDNs (bunkr)
  cyberdrop_dl/crawlers/bunkrr.py
Labels: refactor

#958 fix: do not crash if `last_forum_post` file is missing
  cyberdrop_dl/managers/log_manager.py
Labels: bug

#955 perf: do not parse revisions (kemono)
  cyberdrop_dl/crawlers/kemono.py
Labels: refactor

#954 fix: handle post without files (kemono)
  cyberdrop_dl/crawlers/kemono.py
Labels: bug

#966 refactor: improve cloudflare captcha detection
  cyberdrop_dl/managers/client_manager.py
Labels: refactor

#964 fix: do not close scrape session when using flaresolverr
  cyberdrop_dl/managers/client_manager.py
Labels: bug

#970 feat: add support to albums and searches (ashemaletube)
  cyberdrop_dl/crawlers/ashemaletube.py
Labels: enhancement

#959 fix: videos and images (chevereto)
  cyberdrop_dl/crawlers/_chevereto.py
Labels: bug

#961 fix: add separate post title (xenforo, reddit)
  cyberdrop_dl/crawlers/reddit.py
  cyberdrop_dl/crawlers/xenforo/xenforo.py
Labels: bug

#967 perf: use a single reddit instance
  cyberdrop_dl/crawlers/reddit.py
Labels: refactor

#968 fix: gif downloads (reddit)
  cyberdrop_dl/crawlers/reddit.py
Labels: bug

#972 fix: remove leftover filedate reference
  cyberdrop_dl/utils/sorting.py
Labels: bug

#974 refactor: force remove unsupported entries (auth config file)
  cyberdrop_dl/managers/config_manager.py
Labels: refactor

#978 feat: add box.com support
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/box_dot_com.py
Labels: new website

#980 fix: handle deleted videos (archivebate)
  cyberdrop_dl/crawlers/archivebate.py
Labels: bug

#985 refactor: update supported URL parts (OneDrive)
  cyberdrop_dl/crawlers/onedrive.py
Labels: refactor

#983 fix: `Field object has no attribute close` error
  cyberdrop_dl/managers/cache_manager.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/ui/program_ui.py
Labels: bug

#957 refactor: try to use original server (kemono)
  cyberdrop_dl/crawlers/kemono.py
Labels: refactor

#950 refactor: generalize http request methods
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/utils/utilities.py
  poetry.lock
  pyproject.toml
Labels: refactor

#965 refactor: check DDoS-Guard even on successful pages
  cyberdrop_dl/managers/client_manager.py
Labels: refactor

#942 feat: add buzzheavier support
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/buzzheavier.py
Labels: new website

#986 refactor: add graceful shutdown (again)
  cyberdrop_dl/director.py
Labels: refactor

#992 fix: crawlers http calls
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/crawlers/_chevereto.py
  cyberdrop_dl/crawlers/bunkrr.py
  cyberdrop_dl/crawlers/cyberdrop.py
  cyberdrop_dl/crawlers/cyberfile.py
  cyberdrop_dl/crawlers/dropbox.py
  cyberdrop_dl/crawlers/e621.py
  cyberdrop_dl/crawlers/generic.py
  cyberdrop_dl/crawlers/gofile.py
  cyberdrop_dl/crawlers/google_drive.py
  cyberdrop_dl/crawlers/imgur.py
  cyberdrop_dl/crawlers/jpg5.py
  cyberdrop_dl/crawlers/kemono.py
  cyberdrop_dl/crawlers/luscious.py
  cyberdrop_dl/crawlers/onedrive.py
  cyberdrop_dl/crawlers/pmvhaven.py
  cyberdrop_dl/crawlers/reddit.py
  cyberdrop_dl/crawlers/redgifs.py
  cyberdrop_dl/crawlers/send_now.py
  cyberdrop_dl/crawlers/sex_dot_com.py
  cyberdrop_dl/crawlers/wetransfer.py
  cyberdrop_dl/crawlers/xenforo/celebforum.py
  cyberdrop_dl/crawlers/xenforo/f95zone.py
  cyberdrop_dl/crawlers/xenforo/xenforo.py
  cyberdrop_dl/crawlers/yandex_disk.py
Labels: bug, refactor

#993 refactor: download from the same host as the initial response (doodstream)
  cyberdrop_dl/crawlers/doodstream.py
Labels: refactor

#998 fix: handle more gofile cases
  cyberdrop_dl/crawlers/gofile.py
Labels: bug, refactor

#991 chore: update all dependencies
  .python-version
  poetry.lock
  pyproject.toml
Labels: chore

#990 misc: add script to check dependencies updates
  .gitignore
  scripts/tools/check_dependencies_updates.py
Labels: ci/cd

#1002 style: fix config settings type hints
  cyberdrop_dl/config_definitions/__init__.py
  cyberdrop_dl/config_definitions/config_settings.py
Labels: refactor

#999 feat: add pornhub support
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/pornhub.py
  cyberdrop_dl/utils/css.py
Labels: new website

#994 feat: add imx.to, acidimg and vipr support
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/crawlers/__init__.py
  cyberdrop_dl/crawlers/acidimg.py
  cyberdrop_dl/crawlers/imx_to.py
  cyberdrop_dl/crawlers/vipr_dot_im.py
Labels: new website

#1003 fix: `StopIteration` error when reaching the last page (Kemono)
  cyberdrop_dl/crawlers/kemono.py
Labels: bug, refactor

#962 docs: changelog and wiki updates for v6.10.0 release
  CHANGELOG.md
  docs/reference/cli-arguments.md
  docs/reference/configuration-options/global-settings/general.md
  docs/reference/configuration-options/global-settings/rate-limiting-options.md
  docs/reference/supported-websites.md
Labels: documentation

#981 refactor: add m3u8 module
  cyberdrop_dl/utils/m3u8.py
  poetry.lock
  pyproject.toml
  tests/test_m3u8.py
Labels: refactor

#971 feat: add custom methods for ffprobe (URL and files)
  cyberdrop_dl/data_structures/url_objects.py
  cyberdrop_dl/types.py
  cyberdrop_dl/utils/ffmpeg.py
  cyberdrop_dl/utils/utilities.py
Labels: enhancement

#988 refactor: use system certificates instead of certifi
  cyberdrop_dl/constants.py
  cyberdrop_dl/crawlers/crawler.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/types.py
  poetry.lock
  pyproject.toml
Labels: refactor

#1010 Reduce the number of lines in auto import config
  cyberdrop_dl/ui/prompts/user_prompts.py
  cyberdrop_dl/utils/cookie_management.py
Labels: enhancement, refactor

#1006 test: use pytest temp dir for tests
  cyberdrop_dl/main.py
  tests/test_startup.py
Labels: ci/cd

#1014 fix: disable graceful shutdown
  cyberdrop_dl/director.py
Labels: bug

#1019 fix: profile downloads (chevereto)
  cyberdrop_dl/crawlers/_chevereto.py
  cyberdrop_dl/crawlers/crawler.py
Labels: bug

#1024 refactor: show OS common name in logs
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/utils/utilities.py
Labels: refactor

#1026 fix: jpg5 domain replace
  cyberdrop_dl/crawlers/jpg5.py
Labels: bug

#1031 fix: missing optional argument (kemono)
  cyberdrop_dl/crawlers/_kemono_base.py
Labels: bug
