Repository jbsparrow/CyberDropDownloader, pull requests merged in 2025-02, with the labels that each got.

#550 chore: release v6.4.0
  CHANGELOG.md
  docs/SUMMARY.md
  docs/reference/configuration-options/settings/ignore_options.md
  docs/reference/configuration-options/settings/runtime_options.md
  docs/reference/configuration-options/special_setting_types.md
  pyproject.toml
Labels: chore

#551 docs: update contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#554 fix: delete old rows of previously unsupported URLs
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py
  cyberdrop_dl/scraper/crawlers/pixhost_crawler.py
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/utils/database/tables/history_table.py
Labels: bug

#558 refactor: add custom cloudflare errors + new overrides
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/ui/progress/statistic_progress.py
Labels: refactor

#560 fix: nudostar.tv crawler
  cyberdrop_dl/scraper/crawlers/nudostartv_crawler.py
  cyberdrop_dl/utils/database/tables/history_table.py
Labels: bug

#542 feat: allow downloads of files with no extension
  CHANGELOG.md
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/main.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
  cyberdrop_dl/scraper/crawlers/gofile_crawler.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
  cyberdrop_dl/utils/utilities.py
  docs/reference/configuration-options/settings/ignore_options.md
Labels: enhancement

#565 refactor: drop support for all chromium based browsers on Windows
  cyberdrop_dl/utils/cookie_management.py
  docs/reference/configuration-options/settings/browser_cookies.md
Labels: refactor

#563 fix: check latest version when running from source
  cyberdrop_dl/utils/utilities.py
Labels: bug

#564 refactor: increase verbosity of some processes + fix some log levels
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/bunkrr_albums_io_crawler.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
  cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
  cyberdrop_dl/scraper/crawlers/ehentai_crawler.py
  cyberdrop_dl/scraper/crawlers/eightmuses_crawler.py
  cyberdrop_dl/scraper/crawlers/hotpic_crawler.py
  cyberdrop_dl/scraper/crawlers/imagebam_crawler.py
  cyberdrop_dl/scraper/crawlers/luscious_crawler.py
  cyberdrop_dl/scraper/crawlers/pixhost_crawler.py
  cyberdrop_dl/scraper/crawlers/pornpics_crawler.py
  cyberdrop_dl/scraper/crawlers/realbooru_crawler.py
  cyberdrop_dl/scraper/crawlers/reddit_crawler.py
  cyberdrop_dl/scraper/crawlers/rule34xxx_crawler.py
  cyberdrop_dl/scraper/crawlers/scrolller_crawler.py
  cyberdrop_dl/scraper/crawlers/tiktok_crawler.py
  cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py
  cyberdrop_dl/scraper/crawlers/twitter_images_crawler.py
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
  cyberdrop_dl/scraper/crawlers/xxxbunker_crawler.py
  cyberdrop_dl/scraper/jdownloader.py
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/utils/database/tables/history_table.py
  cyberdrop_dl/utils/sorting.py
Labels: refactor

#545 [Feat] allow restrictions on thread depth
  .gitignore
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
  docs/reference/cli-arguments.md
  docs/reference/configuration-options/settings/download_options.md
Labels: enhancement

#562 docs: wiki and changelog updates for v6.5.0 release
  CHANGELOG.md
  docs/transition-to-v6.md
  poetry.lock
  pyproject.toml
Labels: documentation, chore

#567 fix: `parent_threads` slots for `MediaItem`
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
Labels: bug

#568 fix: console log messages with `--no-ui`
  cyberdrop_dl/managers/live_manager.py
Labels: bug

#546 Feature: Min/Max Audio & Video Duration Config Options
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/managers/download_manager.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
  cyberdrop_dl/utils/database/table_definitions.py
  cyberdrop_dl/utils/database/tables/history_table.py
  docs/SUMMARY.md
  docs/reference/cli-arguments.md
  docs/reference/configuration-options/settings/logs.md
  docs/reference/configuration-options/settings/media_duration_limits.md
Labels: enhancement

#569 fix: media duration check
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/managers/download_manager.py
Labels: bug

#577 fix: log invalid URL paths as scrape errors
  cyberdrop_dl/scraper/crawler.py
Labels: bug

#582 refactor: log CLI only args + system info
  cyberdrop_dl/managers/manager.py
Labels: refactor

#583 refactor: log CLI only args + system info
  cyberdrop_dl/managers/manager.py
Labels: refactor

#585 refactor: enable UI sort option
  cyberdrop_dl/ui/program_ui.py
Labels: refactor

#587 refactor: show queued files in UI progress
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/ui/progress/downloads_progress.py
Labels: refactor

#579 refactor: vacuum requests database
  cyberdrop_dl/ui/program_ui.py
Labels: refactor

#591 refactor: bunkr crawler
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
Labels: bug, refactor

#600 sync: `dev` to `release/v6.5.0`
  docs/transition-to-v6.md
Labels: chore

#605 fix: `yarl.URL` json serialization
  cyberdrop_dl/config_definitions/pydantic/custom_types.py
Labels: bug

#575 fix: handle thumbnail URLs (pixhost)
  cyberdrop_dl/scraper/crawlers/pixhost_crawler.py
Labels: bug

#614 fix: 403s (bunkr)
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
Labels: bug

#610 fix: handle deleted videos (saint)
  cyberdrop_dl/scraper/crawlers/saint_crawler.py
Labels: bug

#617 fix: duplicated entries (pixhost)
  cyberdrop_dl/scraper/crawlers/pixhost_crawler.py
  cyberdrop_dl/utils/database/tables/history_table.py
Labels: bug

#616 fix: extension being assigned to duration (`MediaItem`)
  cyberdrop_dl/scraper/crawler.py
Labels: bug

#598 Xenforo attachment fix
  cyberdrop_dl/utils/utilities.py
Labels: bug

#608 refactor: add javascript utils
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/utils/javascript.py
Labels: refactor

#609 feat: add streamable support
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/streamable_crawler.py
Labels: New Website

#530 refactor: drop v4 support
  CHANGELOG.md
  cyberdrop_dl/config_definitions/authentication_settings.py
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/config_definitions/custom/converters.py
  cyberdrop_dl/config_definitions/custom/types.py
  cyberdrop_dl/config_definitions/custom/validators.py
  cyberdrop_dl/config_definitions/global_settings.py
  cyberdrop_dl/config_definitions/pydantic/validators.py
  cyberdrop_dl/managers/config_manager.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/ui/program_ui.py
  cyberdrop_dl/ui/prompts/user_prompts.py
  cyberdrop_dl/utils/apprise.py
  cyberdrop_dl/utils/args.py
  cyberdrop_dl/utils/transfer.py
  cyberdrop_dl/utils/transfer/__init__.py
  cyberdrop_dl/utils/transfer/backup.py
  cyberdrop_dl/utils/transfer/db_setup.py
  cyberdrop_dl/utils/transfer/transfer_v4_config.py
  cyberdrop_dl/utils/transfer/transfer_v4_db.py
  cyberdrop_dl/utils/transfer/wrapper.py
  docs/reference/cli-arguments.md
  docs/reference/configuration-options/authentication.md
  docs/reference/configuration-options/global-settings/general.md
  docs/reference/configuration-options/global-settings/rate-limiting-options.md
  docs/reference/configuration-options/global-settings/ui-options.md
  docs/reference/configuration-options/settings/browser_cookies.md
  docs/reference/configuration-options/settings/download_options.md
  docs/reference/configuration-options/settings/dupe_cleanup_options.md
  docs/reference/configuration-options/settings/file_size_limits.md
  docs/reference/configuration-options/settings/files.md
  docs/reference/configuration-options/settings/ignore_options.md
  docs/reference/configuration-options/settings/logs.md
  docs/reference/configuration-options/settings/runtime_options.md
  docs/reference/configuration-options/settings/sorting.md
  docs/reference/configuration-options/special_setting_types.md
  docs/reference/supported-websites.md
Labels: refactor

#618 refactor: show input file + input URL count in stats
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/scraper/scraper.py
Labels: refactor

#576 fix: handle attachments with trailing slash (xenforo)
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
  cyberdrop_dl/utils/utilities.py
Labels: bug

#615 feat: add rule34video support
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/rule34video_crawler.py
Labels: New Website

#627 fix: handle deleted files (cyberfile)
  cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py
Labels: bug

#588 refactor: show simplified progress with `--no-ui`
  cyberdrop_dl/main.py
  cyberdrop_dl/managers/live_manager.py
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/ui/progress/downloads_progress.py
  cyberdrop_dl/utils/args.py
Labels: refactor

#628 Feat: Add e621 Support
  CHANGELOG.md
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/e621_crawler.py
  docs/reference/supported-websites.md
Labels: New Website

#642 [chore] change to getting started guide
  README.md
Labels: chore

#650 ci/cd: update issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: ci/cd

#651 feat: try to download files from unsupported forums
  cyberdrop_dl/scraper/filters.py
  cyberdrop_dl/scraper/scraper.py
Labels: enhancement

#649 fix: leakedmodels base domain
  cyberdrop_dl/scraper/crawlers/leakedmodels_crawler.py
Labels: bug

#629 refactor: simplify input URLs load functions + fix URL count
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/utils/database/tables/history_table.py
Labels: bug, refactor

#635 fix: handle malformed responses (flaresolverr)
  cyberdrop_dl/managers/client_manager.py
Labels: bug

#641 fix: handle invalid urls
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
  cyberdrop_dl/utils/utilities.py
Labels: bug

#655 fix: handle URLs with another URL as filename (kemono, coomer, nekohouse)
  cyberdrop_dl/scraper/crawlers/coomer_crawler.py
  cyberdrop_dl/scraper/crawlers/kemono_crawler.py
  cyberdrop_dl/scraper/crawlers/nekohouse_crawler.py
Labels: bug

#654 fix: handle deleted files (mediafire)
  cyberdrop_dl/scraper/crawlers/mediafire_crawler.py
Labels: bug

#646 fix: handle changes in supported sites (config values)
  cyberdrop_dl/config_definitions/config_settings.py
  docs/reference/configuration-options/settings/browser_cookies.md
Labels: bug

#660 ci/cd: update ruff and dependencies
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/ruff.yaml
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/managers/path_manager.py
  cyberdrop_dl/scraper/crawlers/eightmuses_crawler.py
  cyberdrop_dl/scraper/crawlers/eporner_crawler.py
  cyberdrop_dl/scraper/crawlers/spankbang_crawler.py
  cyberdrop_dl/scraper/crawlers/tiktok_crawler.py
  cyberdrop_dl/scraper/crawlers/youjizz_crawler.py
  cyberdrop_dl/ui/progress/deque_progress.py
  cyberdrop_dl/utils/yaml.py
  poetry.lock
  pyproject.toml
  tests/test_apprise.py
Labels: bug, ci/cd

#661 refactor: auto update wiki CLI overview
  cyberdrop_dl/utils/args.py
Labels: refactor

#662 Fix: fix handle_direct_links for bunkr cdn urls
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
  cyberdrop_dl/utils/constants.py
  cyberdrop_dl/utils/utilities.py
Labels: bug

#665 fix: do not download known invalid files
  cyberdrop_dl/downloader/downloader.py
Labels: bug

#663 refactor: reduce gofile request limiter
  cyberdrop_dl/scraper/crawlers/gofile_crawler.py
Labels: refactor

#664 refactor: add missing thousand separators
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/ui/progress/deque_progress.py
  cyberdrop_dl/ui/progress/statistic_progress.py
Labels: refactor

#673 refactor: remove left padding from log files
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/main.py
  cyberdrop_dl/utils/logger.py
Labels: refactor

#666 fix: reddit referers
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/scraper/crawlers/reddit_crawler.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
Labels: bug

#690 fix: stream URL check (bunkr)
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
Labels: bug

#691 fix: false positive `FailedLogin` errors
  cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
Labels: bug

#685 fix: handle more 404 cases (saint)
  cyberdrop_dl/scraper/crawlers/saint_crawler.py
Labels: bug

#675 refactor: better error messages for invalid configs
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/main.py
  cyberdrop_dl/managers/config_manager.py
  cyberdrop_dl/utils/apprise.py
  cyberdrop_dl/utils/constants.py
  cyberdrop_dl/utils/yaml.py
Labels: bug

#677 refactor: validate regex at startup
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/managers/config_manager.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/scraper/crawler.py
Labels: refactor

#687 fix: handle empty responses from flaresolverr
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/managers/client_manager.py
Labels: bug

#678 refactor: move profiling to its own module
  cyberdrop_dl/env.py
  cyberdrop_dl/main.py
  cyberdrop_dl/profiling.py
Labels: refactor

#686 refactor: always append date when DEBUG_LOG_FOLDER env var is used
  cyberdrop_dl/env.py
  cyberdrop_dl/main.py
Labels: refactor

#636 docs: wiki and changelog updates for v6.6.0 release
  CHANGELOG.md
  docs/reference/cli-arguments.md
  docs/reference/supported-websites.md
  docs/transition-to-v6.md
  poetry.lock
  pyproject.toml
Labels: documentation, chore

#679 feat: improve hotpic crawler
  cyberdrop_dl/scraper/crawlers/hotpic_crawler.py
Labels: enhancement

#688 fix: use async locks for flaresolverr
  cyberdrop_dl/managers/client_manager.py
Labels: bug

#680 refactor: redefine some `Crawler` methods as `ScrapeItem` method
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
Labels: refactor

#693 refactor: report downloads with no content type as `InvalidContentType`
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/managers/client_manager.py
Labels: refactor

#696 refactor: log unexpected responses from forums
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
Labels: refactor

#668 fix: handle errors while checking for updates
  cyberdrop_dl/main.py
  cyberdrop_dl/ui/program_ui.py
  cyberdrop_dl/utils/constants.py
  cyberdrop_dl/utils/updates.py
  cyberdrop_dl/utils/utilities.py
Labels: bug

#695 fix: `File is being used by another process` error if a validation error raises when running multiple configs
  cyberdrop_dl/main.py
  cyberdrop_dl/utils/constants.py
Labels: bug

#703 fix: regression - do not remove trailing slash from URLs (chevereto)
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
Labels: bug

#705 fix: messages always being logged to the console
  cyberdrop_dl/main.py
Labels: bug

#704 fix: handle OS errors on startup (log files)
  cyberdrop_dl/env.py
  cyberdrop_dl/main.py
  cyberdrop_dl/profiling.py
  cyberdrop_dl/scraper/__init__.py
Labels: bug

#714 fix: use new api to get file (bunkr)
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
Labels: bug

#720 Feature: Add Hyperlinks to Logged Paths
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/utils/logger.py
Labels: enhancement

#701 docs: wiki and changelog updates for v6.6.1 release
  CHANGELOG.md
Labels: documentation, chore

#710 refactor: log URL count on startup
  cyberdrop_dl/scraper/filters.py
  cyberdrop_dl/scraper/scraper.py
Labels: refactor

#689 feat: show status messages at the bottom of the UI
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/scraper/scraper.py
Labels: enhancement

#697 refactor: deprecate forum auth (username and password)
  cyberdrop_dl/config_definitions/authentication_settings.py
  cyberdrop_dl/managers/manager.py
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
  cyberdrop_dl/utils/cookie_management.py
Labels: refactor

#683 feat: add wetransfer support
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/wetransfer_crawler.py
Labels: new website

#681 feat: add dirtyship support
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/dirtyship_crawler.py
Labels: new website

#676 feat: add `--dump-json` option
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/clients/hash_client.py
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/main.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
  cyberdrop_dl/utils/dumper.py
Labels: enhancement

#723 fix: don't save hyperlink markup to the main log file
  cyberdrop_dl/utils/logger.py
  poetry.lock
  pyproject.toml
Labels: bug

#708 fix: parsing of filenames from unsupported forums
  cyberdrop_dl/utils/constants.py
  cyberdrop_dl/utils/utilities.py
Labels: bug

#712 feat: add yandex disk support
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/yandex_disk_crawler.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
Labels: new website

#729 fix: remove recursive requests calls and recursive locks from flaresolverr class
  cyberdrop_dl/managers/client_manager.py
Labels: bug

#728 refactor: simplify error message logging
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/managers/log_manager.py
  cyberdrop_dl/utils/utilities.py
Labels: refactor

#726 fix: get URL from encrypted link (jpg5)
  cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
Labels: bug

#727 fix: do not check content type in headers
  cyberdrop_dl/clients/download_client.py
Labels: bug

#669 feat: add google drive support
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/google_drive_crawler.py
Labels: refactor, new website

#670 feat: add dropbox support
  cyberdrop_dl/clients/scraper_client.py
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawlers/dropbox_crawler.py
  cyberdrop_dl/utils/args.py
Labels: new website

#706 ci/cd: run tests with matrix in ci
  .github/workflows/ci.yml
  cyberdrop_dl/main.py
  cyberdrop_dl/profiling.py
  cyberdrop_dl/utils/args.py
  poetry.lock
  pyproject.toml
  tests/test_cli.py
  tox.ini
Labels: ci/cd

#715 feat: add portrait layout
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/ui/progress/file_progress.py
  cyberdrop_dl/ui/progress/scraping_progress.py
  cyberdrop_dl/utils/args.py
Labels: enhancement

#721 chore: release v6.6.1
  CHANGELOG.md
  cyberdrop_dl/clients/download_client.py
  cyberdrop_dl/clients/errors.py
  cyberdrop_dl/config_definitions/config_settings.py
  cyberdrop_dl/downloader/downloader.py
  cyberdrop_dl/env.py
  cyberdrop_dl/main.py
  cyberdrop_dl/managers/client_manager.py
  cyberdrop_dl/managers/log_manager.py
  cyberdrop_dl/managers/progress_manager.py
  cyberdrop_dl/profiling.py
  cyberdrop_dl/scraper/__init__.py
  cyberdrop_dl/scraper/crawler.py
  cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
  cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
  cyberdrop_dl/scraper/crawlers/tiktok_crawler.py
  cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
  cyberdrop_dl/scraper/crawlers/youjizz_crawler.py
  cyberdrop_dl/scraper/filters.py
  cyberdrop_dl/scraper/scraper.py
  cyberdrop_dl/ui/program_ui.py
  cyberdrop_dl/utils/constants.py
  cyberdrop_dl/utils/data_enums_classes/url_objects.py
  cyberdrop_dl/utils/logger.py
  cyberdrop_dl/utils/updates.py
  cyberdrop_dl/utils/utilities.py
  poetry.lock
  pyproject.toml
Labels: chore
